### Calibration test
POST https://localhost:5001/api/trebuchet/calibration
Content-Type: text/plain

< ./Calibration/TestInput.txt

### Calibration
POST https://localhost:5001/api/trebuchet/calibration
Content-Type: text/plain

< ./Calibration/Input.txt

### Advanced Calibration Test
POST https://localhost:5001/api/trebuchet/advanced-calibration
Content-Type: text/plain

< ./AdvancedCalibration/TestInput.txt

### Advanced Calibration
POST https://localhost:5001/api/trebuchet/advanced-calibration
Content-Type: text/plain

< ./AdvancedCalibration/Input.txt